### ISSUE TITLE
Suggestion: rename context menu item to 'Duplicate Tab'

### ISSUE THREAD

**Issue by GAJansen** [stefansundin/duplicate-tab#1]
I am running Firefox Nightly and installed 'duplicate-tab', and the add-on works fine, well done Stefan.

However, to keep the naming in the context menu on par with Firefox's other Tab-related items (in the context menu: _Reload Tab, Mute Tab, Pin Tab, Close Tab_, etc) I suggest you rename the item '_Duplicate_' to '**Duplicate Tab**'.

**Comment by stefansundin** [comment]
Hi!

The reason I named it just "Duplicate" is because that's what Chrome calls it.

But you're right, it is a bit weird, it should probably be called "Duplicate Tab". I will probably rename it as you suggest.

Thanks!
