### ISSUE TITLE
New tab now is placed at the right end of tabs

### ISSUE THREAD

**Issue by exec228** [stefansundin/duplicate-tab#11]
Salut!

A time ago, a duplicate tab was inserted right after current tab, which was the killer feature I chose this addon amongst others.

Nowadays, a duplicate tab is added loooong way right, at the end of tabs.

Is there any hope that dup-tab will be placed adjacent to a current tab?

**Comment by stefansundin** [comment]
Hello!

My duplicated tabs are still inserted right after the current tab. Not sure why your behavior is different.

Does right clicking the tab and selecting "Duplicate" also put it at the far right? I think that should basically be triggering the same thing in Chrome.

Are you using Chrome or Firefox?

**Comment by exec228** [comment]
Right-Click\Context|Duplicate tab\ always created a new tab at the right.
I have Firefox 77.0.1x64 with
> browser.tabs.insertAfterCurrent=false
> browser.tabs.insertRelatedAfterCurrent=false
since long ago, may be ten years already.

That is: your extension inserted duplicate as an *utlimately* related tab just right of the source tab.
And this is what I especially liked your extension for.
