### ISSUE TITLE
Does not work in incognito mode

### ISSUE THREAD

**Issue by jaffasplaffa** [stefansundin/duplicate-tab#17]
Hey :) 

I noticed that none of the functions works when in incognito mode.

Are there any plans to update the extension, so it works in incognito mode too?

Thanks,
Jakob

**Comment by stefansundin** [comment]
Hello @jaffasplaffa,

Are you using Chrome or Firefox?

Have you allowed the extension to run in incognito mode? This is an extra action after installing it.

In Chrome, go to the list of your installed extensions, find Duplicate Tab Shortcut, and click <kbd>Details</kbd>. Then find the toggle for `Allow in Incognito` and enable it.

Screenshot:

![Screenshot 2023-01-22 at 11 55 56](https://user-images.githubusercontent.com/1991151/213937444-01c71f50-b58c-40b8-ae21-17397643aef1.png)

You can go directly to this page by copy-pasting the following into your URL bar:

```
chrome://extensions/?id=klehggjefofgiajjfpoebdidnpjmljhb
```

**Comment by jaffasplaffa** [comment]
Haaaaww man, completely missed that option.

I apologize, I got it working now thanks!

And thanks for the extension BTW ;)

**Comment by stefansundin** [comment]
Awesome 👍

**Comment by thadikari** [comment]
Hi [stefansundin](https://github.com/stefansundin), thanks for the awesome tool! I have a quick incognito-related follow-up.

Is there a "Pop tab out to a new INCOGNITO window shortcut"?
E.g., the current tab is in non-incognito mode, and I want to duplicate that tab in a new INCOGNITO window.

I understand that the original issue in this thread is closed, so if you want me to open a new issue for this, let me know. Thanks!
