### ISSUE TITLE
Feature request: place 'duplicate-tab' in context among first items

### ISSUE THREAD

**Issue by GAJansen** [stefansundin/duplicate-tab#2]
In most browsers (Opera, Chromium/Chrome, Vivaldi, etc) the option of tab-duplication is already built-in, but not so in Firefox. 

As I use many browsers, I noticed that the 'Duplicate Tab / Clone Tab' item is usually in the upper section of the context menu, as second (Opera) or third (Chromium, Google Chrome, Vivaldi) item.

So my request is: can you place the 'Duplicate Tab' item for Firefox as the first item of the context menu? The context-menu items that come with Firefox and are listed on top (Reload Tab, Mute Tab) are probably less used by anyone, so 'Duplicate Tab' being the first item of the list would be right in my opinion.

**Comment by stefansundin** [comment]
I couldn't find a way to put it further up. I can't find anything in the documentation that would allow me to do it. I could be wrong though.

- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus/create
- https://developer.chrome.com/extensions/contextMenus

**Comment by monk-time** [comment]
@stefansundin In FF57 this is no longer needed as a context menu item was added in [Bug 455722](https://bugzilla.mozilla.org/show_bug.cgi?id=455722). And the item added by the extension is also no longer necessary.

**Comment by stefansundin** [comment]
Neat, thanks for the heads up. It's interesting that the bug is 9 years old. :)
