### ISSUE TITLE
Open tab in background

### ISSUE THREAD

**Issue by impman** [stefansundin/duplicate-tab#3]
Found a way to either immediately switch to the duplicated tab, or to disable switching altogether, leaving it in the background. Right now there's a delay while the tab loads before switching to it.

In background.js replace the duplicate command with:

`chrome.tabs.create({active:true,openerTabId:tab.id,url:tab.url});`

and to manifest.json add:

`"permissions": ["tabs"],`

setting active:false allows for opening tabs in the background, perhaps there can be an option to switch this somewhere.

**Comment by stefansundin** [comment]
Thanks! I pushed a new version for both Chrome and Firefox (v1.3.0). As you mentioned, this improves the behavior in Firefox because there's a strange delay before the new tab is switched to. I wonder why that is.

**Comment by nmaster64** [comment]
FYI, this change now makes Chrome ask for "Read your browsing history" permissions, which I almost removed the extension for. If you're going to leave it in, I highly recommend adding an explanation to the description on the store.

**Comment by stefansundin** [comment]
I put it in there, but you had to scroll down to see it. I decided to remove most of the unnecessary text in order to make it much simpler and easy. Thanks!
