### ISSUE TITLE
Should duplicate a tab instead of opening a new tab with the same URL

### ISSUE THREAD

**Issue by lastorset** [stefansundin/duplicate-tab#6]
Instead of using Firefox's duplication functionality (accessible using the tab context menu), this extension just opens a new tab with the same URL. The duplication feature also copies history.

The [tabs.duplicate](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/duplicate) API looks like what is needed. I used the corresponding API for the [tab-keys](https://github.com/lastorset/tab-keys/blob/master/js/background.js) extension for Opera, though it appears to be promise-oriented in Firefox, so would need a slightly different implemention.

**Comment by lastorset** [comment]
Hm, I just saw that this was changed for #3. I was happy at first that delay was gone. :) As an alternate solution, perhaps the `duplicate` call should be reinstated with a callback on the duplicated tab to activate it immediately?

Also, in my comment above I was confused by the two APIs, the `chrome` callback-oriented one, which this extension uses, and the promise-oriented `browser` API.

**Comment by stefansundin** [comment]
I didn't think about the history not being duplicated. You are right that it is a bad side effect.

Hopefully they will fix the delay in a future Firefox release. For now you can install the old version: https://addons.mozilla.org/en-US/firefox/addon/duplicate-tab-shortcut/versions/1.2.0

When I get some time, I'll try switching back to duplicate and changing the active tab. If it works well, I'll release an update.

Thanks for the report!

**Comment by stefansundin** [comment]
This was changed back in v1.4.0 that was just released. The `duplicate` function is now used if the new tabs are not opened in the background.
