### ISSUE TITLE
Can't use Ctrl+Alt+something hotkeys?

### ISSUE THREAD

**Issue by R-OLE** [stefansundin/duplicate-tab#9]
I've used Firefox for years configured for Ctrl+Alt+T for duplicating a tab, and would like to keep it.

When attempting to setup a different hotkey, the user interface refuses to accept simultaneous Ctrl+Alt key modifiers.
Is this an artificial limitation of your code, or something about the API you employ, or something else?

Using Chrome Version 68.0.3440.106.

**Comment by stefansundin** [comment]
Hi!

The chrome://extensions/shortcuts page is created by Chrome, and I am not able to assign any Ctrl+Alt shortcuts there. Was this possible before? If so, they might have disabled it at some point.

I don't think there's any other way for me to configure a shortcut. I am not able to use Ctrl+Alt on Firefox either.

Sorry, I don't think there's anything I can do. Let me know if you find a solution.
